apply plugin: 'com.android.application'

android {
    namespace 'bd.com.diamu'
    compileSdk 35

    def versionMajor = 1
    def versionMinor = 1
    def versionPatch = 1
    bundle {
        language {
            enableSplit = false
        }
    }

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        applicationId "bd.com.diamu"
        minSdk 21
        targetSdk 33
        versionCode versionMajor + versionMinor + versionPatch
        versionName "${versionMajor}.${versionMinor}.${versionPatch}"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        multiDexEnabled true
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }

    signingConfigs {
        release {
            storeFile file("/$project.rootDir/diamu-shopping.jks")
            storePassword STORE_PASSWORD
            keyAlias "diamu-shopping"
            keyPassword KEY_PASSWORD
        }
    }

    buildTypes {
        debug {
            versionNameSuffix '-DEBUG'
            debuggable true
            minifyEnabled false
            signingConfig signingConfigs.debug
        }

        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    ext {
        APP_NAME = "@string/app_name"
        APP_NAME_STAG = "@string/app_name_stag"
    }

    flavorDimensions = ["version"]

    productFlavors {
        stag {
            dimension "version"
            versionNameSuffix "-STAG"
            manifestPlaceholders = [appName: APP_NAME_STAG]
            buildConfigField "String", "BASE_URL", '\"https://diamu.com.bd/\"'
        }

        prod {
            dimension "version"
            versionNameSuffix "-PROD"
            manifestPlaceholders = [appName: APP_NAME]
            buildConfigField "String", "BASE_URL", '\"https://diamu.com.bd/\"'
        }
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            def project = "DIAMU-SHOPPING-APP"
            def separator = "-"
            def version = variant.versionName
            def date = new Date()
            def formattedDate = date.format('yyyy-MM-dd-HH-mm')
            def newApkName = "$project$separator$version$separator${formattedDate}.apk"

            outputFileName = new File(newApkName)
        }
    }

    viewBinding {
        enabled true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding true
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'com.android.support:multidex:2.0.1'
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
